### ISSUE TITLE
No sensor class calls Sensor::init()

### ISSUE THREAD

**Issue by steph643** [askuric/Arduino-FOC#121]
For example `MagneticSensorSPI` never calls `Sensor::init()`. I believe this causes `Sensor::full_rotations` to be wrongly computed during the first call to `Sensor::update()`.

**Comment by askuric** [comment]
Hey @steph643,
The sensor init is delegated to the user. The user has to call it before linking the sensor to the motor.
I am not sure if that makes sense in your case.

Do you still have the same issue with miscalculated values even after the  init call?

**Comment by runger1101001** [comment]
This is my bad - I can't believe I missed this! I fear it is because I normally use the specific sensor implementations I have created in the Arduino-FOC-drivers repository. Those all call the base class init method... doh! silly and careless me!

I think Encoder and HallSensor don't need it, since their velocity calculations are handled in the specific classes overriding the base class. The other sensors all need it.

I have fixed it in my fork: https://github.com/runger1101001/Arduino-FOC/tree/dev
and created a pull request against the dev branch. I won't merge it just yet because I'm on vacation and can't test with a real sensor and motor.
